# curl -v -XPOST -u client:secret "http://localhost:8080/oauth/token?grant_type=password&username=john&password=12345&scope=read"
POST http://localhost:8080/oauth/token?grant_type=password&username=john&password=12345&scope=read
Authorization: Basic client secret

###

# curl -u client:secret -XPOST http://localhost:8080/oauth/token?grant_type=authorization_code&username=user&password=12345&scope=read
POST http://localhost:8080/oauth/token?grant_type=password&username=petro&password=password&scope=scope
Authorization: Basic client_id secret

###

GET  http://localhost:8080/client
Content-Type: application/json

###

POST  http://localhost:8080/client
Content-Type: application/json

{
  "client_id": "client_id",
  "secret": "secret",
  "scope": "scope",
  "redirectUri": "localhost",
  "grantTypes": [
    {
      "grantType": "password"
    },
    {
      "grantType": "authorization_code"
    },
    {
      "grantType": "refresh_token"
    }
  ]
}

###

GET  http://localhost:8080/user
Content-Type: application/json

###

POST  http://localhost:8080/user
Content-Type: application/json

{
  "username": "petro",
  "password": "password"
}

###

